[tool.black]
line-length = 120
target_version = ["py39"]

[tool.isort]
profile = "black"
include_trailing_comma = true
combine_as_imports = true

[tool.mypy]
# Basic mypy configuration.
check_untyped_defs = true
explicit_package_bases = true
follow_imports = "silent"
ignore_missing_imports = true
namespace_packages = true
pretty = true
python_version = "3.9"
show_error_codes = true
strict_optional = true
plugins = "numpy.typing.mypy_plugin"


# Lint rules.
allow_redefinition = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_reexport = true
no_implicit_optional = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true
warn_unused_configs = true
warn_unreachable = true


[tool.pylint.'MASTER']
jobs = 4

[tool.pylint.'FORMAT']
max-line-length=120


