build_pg: False
build_bbase: False
pg_prewarm: True
pg_stat_statements: True
pg_store_plans: True
auto_explain: True
bench_dbs: [tpcc]
# bench_dbs: [tpcc, tatp, ycsb, wikipedia, voter, twitter, smallbank, auctionmark]
sqlsmith: False # currently ignored because dataset naming gets weird
log_level: INFO
debug: True
